name: Zim-MD 
services:
  - name: Zim-MD-service
    type: web
    ports:
      - 3000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
